a = input('Digite algo: ')
print(f'{a} pertence a qual tipo primitivo?')
print(type(a))
print(f'{a} só tem espaços?', (a.isspace()))
print(f'{a} é um número?', (a.isnumeric()))
print(f'{a} é alfabético?', (a.isalpha()))
print(f'{a} é alfanumérico?', (a.isalnum()))
print(f'{a} está em maiúsculo?', (a.isupper()))
print(f'{a} está em minúsculo?', (a.islower()))
print(f'{a} está capitalizado?', (a.istitle()))
