print('Conversor de medidas')
m = float(input('Digite uma medida em METROS: '))
print(f'A medida de {m} corresponde a:')
print(f'{m/10/10/10:.4f}km')
print(f'{m/10/10:.3f}hm')
print(f'{m/10}dam')
print(f'{m*10}dm')
print(f'{m*10*10}cm')
print(f'{m*10*10*10}mm')
