print(' Analisador de Textos')
nome = input('Digite seu nome: ').strip()
print(f'Seu nome em maiúsculas é: {nome.upper()}')
print(f'Seu nome em minúsculas é: {nome.lower()}')
print(f'Seu nome tem {len(nome) - nome.count(' ')} letras.')
print(f'Seu primeiro nome é {nome.split()[0]}! e tem {len(nome.split()[0])} letras!')
# print(f'Seu primeiro nome é {nome.split()[0]} e tem {nome.find(' ')} letras')
# separa = nome.split()
# print(f'Seu primeiro nome é {separa[0]} e tem {len(separa[0])} letras')
